// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6e42SWz5CxxeO2ErHOj8BYekCSWBtovQ',
    appId: '1:295940652160:web:6bd7cd1c1d2314272a7a65',
    messagingSenderId: '295940652160',
    projectId: 'psycospace-mobile',
    authDomain: 'psycospace-mobile.firebaseapp.com',
    storageBucket: 'psycospace-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW4GAMwEUSnfgXY4ODu6dpA5tswpwZ7NY',
    appId: '1:295940652160:android:34dcccb7e12281352a7a65',
    messagingSenderId: '295940652160',
    projectId: 'psycospace-mobile',
    storageBucket: 'psycospace-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYBKQVsWSngFs8X3JKu5bVj3R1ELSgr2I',
    appId: '1:295940652160:ios:883d891e7e6201c22a7a65',
    messagingSenderId: '295940652160',
    projectId: 'psycospace-mobile',
    storageBucket: 'psycospace-mobile.appspot.com',
    iosClientId: '295940652160-3urfqvufj61jrsrkh3ud83gni3kgk6dm.apps.googleusercontent.com',
    iosBundleId: 'com.example.psycoSpace',
  );
}
